name: Python Static Analysis and Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0-rc.1'

    - name: Install dependencies
      run: |
        pip install autopep8 pylint pyright pytest

    - name: Autopep8 (Auto format code)
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "AUTOPEP8_STATUS=Pass" >> $GITHUB_ENV
        else
          echo "AUTOPEP8_STATUS=Fail" >> $GITHUB_ENV
        fi
        
    - name: Create AutoPEP8 Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 610c5444484d8b7e11764786357f1075
        filename: autopep8.json
        label: AutoPEP8
        message: ${{ env.AUTOPEP8_STATUS }}
        color: ${{ env.AUTOPEP8_STATUS == 'Pass' && 'green' || 'red' }}

    - name: Run Pylint (Static analysis)
      run: |
        pylint hw2_debugging.py rand.py
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "PYLINT_STATUS=Pass" >> $GITHUB_ENV
        else
          echo "PYLINT_STATUS=Fail" >> $GITHUB_ENV
        fi
            
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 08bfddaeaa50b18120b40f0118cc6228
        filename: pylint.json
        label: Pylint
        message: ${{ env.PYLINT_STATUS }}
        color: ${{ env.PYLINT_STATUS == 'Pass' && 'green' || 'red' }}

    - name: Run pyright (Style check)
      run: |
        pyright hw2_debugging.py rand.py
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "PYRIGHT_STATUS=Pass" >> $GITHUB_ENV
        else
          echo "PYRIGHT_STATUS=Fail" >> $GITHUB_ENV
        fi
        
    - name: Create Pyright Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: eda49634ad4b5d5f829e8ade4d6f138c
        filename: pyright.json
        label: Pyright
        message: ${{ env.PYRIGHT_STATUS }}
        color: ${{ env.PYRIGHT_STATUS == 'Pass' && 'green' || 'red' }}

    - name: Run Tests with pytest
      run: |
        pytest
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "PYTEST_STATUS=Pass" >> $GITHUB_ENV
        else
          echo "PYTEST_STATUS=Fail" >> $GITHUB_ENV
        fi

    - name: Create Pytest Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: a9e2ae393657421b37b65cc6d8c3756e
        filename: pytest.json
        label: Pytest
        message: ${{ env.PYTEST_STATUS }}
        color: ${{ env.PYTEST_STATUS == 'Pass' && 'green' || 'red' }}
